scan_timeout = 10

[character]
error_symbol = "[â¯â¯](bold red)"
success_symbol = "[â¯â¯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"

[docker_context]
format = "via [ðŸ³ $context ](blue bold)"

[git_branch]
symbol = "ïˆ "

[custom.git_username]
command = "git config user.name"
when = "git rev-parse --git-dir 2> /dev/null"
format = "by [$output]($style) "
style = "bright-yellow bold"

[gcloud]
disabled = true

[time]
disabled = false
format = "at [ðŸ•™ $time]($style) "
utc_time_offset = "+9"

[username]
disabled = true

